Add tests, README to elasticsearch
Also:
- move contacts/*elasticsearch* files to docker/elasticsearch since they
  are unique to mongo

diff --git a/docker/elasticsearch/makefile b/docker/elasticsearch/makefile
--- a/docker/elasticsearch/makefile
+++ b/docker/elasticsearch/makefile
@@ -15,13 +15,21 @@ RUN_ARGS := -p 9200:9200 -p 9300:9300 -e "http.host=0.0.0.0" -e "transport.host=
 
 # I am a pre-req to 'clean' and perform non-docker cleanup
 clean_local:
-	@rm -f seed-data.json
-
-seed-data.json: ../../contacts/us-500.elasticsearch
-	cp $< seed-data.json
 
 # I am a pre-req to 'build' and perform all pre-build operations
-setup_local: seed-data.json
+setup_local:
 
 # I am a pre-req to 'test' and perform all testing on the provided, running container
 test_local:
+	@echo "===> Testing data row count is correct"
+	$(eval ROW_COUNT := $(shell curl -s elastic:changeme@localhost:9200/_cat/count/contacts))
+
+	@# ROW_COUNT is the third word in the result
+	$(eval ROW_COUNT := $(word 3, $(ROW_COUNT)))
+
+	@if [ "$(ROW_COUNT)" == "500" ]; then \
+		echo "     $(IMAGE_NAME) has the correct row count ($(ROW_COUNT))"; \
+	else \
+		echo "===> ERROR: $(IMAGE_NAME) does not have the correct row count. Expected: '500', Actual: '$(ROW_COUNT)'"; \
+		exit 2; \
+	fi
