Fix postgres 'test' account access
Also:
- add postgres, percona READMEs
- add postgres 'test' account tests
- add percona tests
- fix run* targets to execute appropriately

diff --git a/docker/percona/makefile b/docker/percona/makefile
--- a/docker/percona/makefile
+++ b/docker/percona/makefile
@@ -18,11 +18,36 @@ clean_local:
 	@rm -f seed-data.sql
 
 seed-data.sql: ../../contacts/us-500.mysql.sql
-	@## Prepend our test schema to the contacts schema
+	@# Prepend our test schema to the contacts schema
 	@cat test-schema.sql $< > seed-data.sql
 
 # I am a pre-req to 'build' and perform all pre-build operations
 setup_local: seed-data.sql
 
-# I am a pre-req to 'test' and perform all testing on a running container
+# I am a pre-req to 'test' and perform all testing on the provided, running container
 test_local:
+	@echo "===> Testing data row count is correct"
+	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) mysql -uroot -proot -Dtest -s --skip-column-names -e 'SELECT COUNT(*) from test.contacts;'))
+
+	@# mysql prints a warning so our output looks like:
+	@#  mysql: [Warning] Using a password on the command line interface can be insecure. 500
+	@# we will sort the response and take the first word to capture row count
+	$(eval ROW_COUNT := $(word 1, $(sort $(ROW_COUNT))))
+
+	@if [ "$(ROW_COUNT)" == "500" ]; then \
+		echo "     $(IMAGE_NAME) has the correct row count ($(ROW_COUNT))"; \
+	else \
+		echo "===> ERROR: $(IMAGE_NAME) does not have the correct row count. Expected: '500', Actual: '$(ROW_COUNT)'"; \
+		exit 2; \
+	fi
+
+	@echo "===> Testing 'test' account access"
+	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) mysql -utest -ptest -D test -s --skip-column-names -e 'SELECT COUNT(*) from test.contacts;'))
+	$(eval ROW_COUNT := $(word 1, $(sort $(ROW_COUNT))))
+
+	@if [ "$(ROW_COUNT)" == "500" ]; then \
+		echo "     $(IMAGE_NAME) allows 'test' account access to 'test' database"; \
+	else \
+		echo "===> ERROR: $(IMAGE_NAME) does not allows 'test' account access to 'test' database"; \
+		exit 2; \
+	fi
diff --git a/docker/postgres/makefile b/docker/postgres/makefile
--- a/docker/postgres/makefile
+++ b/docker/postgres/makefile
@@ -19,12 +19,24 @@ clean_local:
 # I am a pre-req to 'build' and perform all pre-build operations
 setup_local:
 
-# I am a pre-req to 'test' and perform all testing on a running container
+# I am a pre-req to 'test' and perform all testing on the provided, running container
 test_local:
-	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) psql -t -U postgres -d test -c 'SELECT COUNT(*) FROM contacts;'))
+	@echo "===> Testing data row count is correct"
+	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) psql postgres://postgres@localhost/test -t -c 'SELECT COUNT(*) FROM test.contacts;'))
+
 	@if [ "$(ROW_COUNT)" == "500" ]; then \
-		echo "===> $(IMAGE_NAME) has the correct row count ($(ROW_COUNT))"; \
+		echo "     $(IMAGE_NAME) has the correct row count ($(ROW_COUNT))"; \
 	else \
-		echo "===> $(IMAGE_NAME) does not have the correct row count ($(ROW_COUNT))"; \
+		echo "===> ERROR: $(IMAGE_NAME) does not have the correct row count. Expected: '500', Actual: '$(ROW_COUNT)'"; \
+		exit 2; \
+	fi
+
+	@echo "===> Testing 'test' account access"
+	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) psql postgres://test:dGVzdA==@localhost/test -t -c 'SELECT COUNT(*) FROM test.contacts;'))
+
+	@if [ "$(ROW_COUNT)" == "500" ]; then \
+		echo "     $(IMAGE_NAME) allows 'test' account access to 'test' database"; \
+	else \
+		echo "===> ERROR: $(IMAGE_NAME) does not allows 'test' account access to 'test' database"; \
 		exit 2; \
 	fi
