Add tests, README to mongo
Also:
- move contacts/*mongo* files to docker/mongo since they are unique to mongo

diff --git a/docker/mongo/makefile b/docker/mongo/makefile
--- a/docker/mongo/makefile
+++ b/docker/mongo/makefile
@@ -19,13 +19,18 @@ RUN_ARGS := -p 27017:27017
 
 # I am a pre-req to 'clean' and perform non-docker cleanup
 clean_local:
-	@rm -f seed-data.js
-
-seed-data.js: ../../contacts/us-500.mongo.js
-	cp $< seed-data.js
 
 # I am a pre-req to 'build' and perform all pre-build operations
-setup_local: seed-data.js
+setup_local:
 
 # I am a pre-req to 'test' and perform all testing on the provided, running container
 test_local:
+	@echo "===> Testing data doc count is correct"
+	$(eval ROW_COUNT := $(shell docker exec -it $(IMAGE_NAME) mongo test --quiet --eval 'db.contacts.count();'))
+
+	@if [ "$(ROW_COUNT)" == "500" ]; then \
+		echo "     $(IMAGE_NAME) has the correct row count ($(ROW_COUNT))"; \
+	else \
+		echo "===> ERROR: $(IMAGE_NAME) does not have the correct row count. Expected: '500', Actual: '$(ROW_COUNT)'"; \
+		exit 2; \
+	fi
